// Code generated by entc, DO NOT EDIT.

package ent

import "user-service/internal/biz"

func (uu *UserUpdate) SetUser(input *biz.User) *UserUpdate {

	uu.SetNillableUsername(input.Username)

	uu.SetNillablePassword(input.Password)

	uu.SetNillableCreatedAt(input.CreatedAt)

	uu.SetNillableUpdatedAt(input.UpdatedAt)
	return uu
}

func (uc *UserCreate) SetUser(input *biz.User) *UserCreate {

	uc.SetNillableUsername(input.Username)

	uc.SetNillablePassword(input.Password)

	uc.SetNillableCreatedAt(input.CreatedAt)

	uc.SetNillableUpdatedAt(input.UpdatedAt)
	return uc
}
